### ISSUE TITLE
Does it work for multi-class classification?

### ISSUE THREAD

**Issue by JiaenWu** [zhongcheng0519/libsvm_for_embeded#1]
Hi, Zhongcheng,

Thanks for your great contribution. It works pretty well for two class classification. But when I test the model for more than two class, it complains:
cat ../data.txt|./svm_test 
zsh: done                cat ../data.txt | 
zsh: segmentation fault  ./svm_test

Do you have any idea why this happens?
Thanks in advance.

**Comment by zhongcheng0519** [comment]
Sorry that we are in Spring Festival holiday currently. So I didn't see your comment until right now. 
The problem you encountered is which I didn't test as in my application, only two class classification is used.
Thank you for your bug reporting, I'll fix the bug in a few days.

**Comment by zhongcheng0519** [comment]
Sorry that we are in Spring Festival holiday currently. So I didn't see your comment until right now.
The problem you encountered is the case I didn't handle. As in my application, only two class classification is enough, and I don't think its an easy work to support multi-class classification.

Wishes you could contribute your code of multi-class classification. Thank you!
